server:
  port: 8080
  servlet:
    context-path: /todo/api/v1

spring:
  application:
    name: ${APPLICATION_NAME:TodoApp}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgresuser
    password: postgresuser
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          default_schema: public

  # Uncomment the following section if you want to use H2 console
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  logging:
    level:
      root: INFO
      com.soprasteria.todo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Uncomment the following section if you want to configure SpringDoc
#  spring-doc:
#    api-docs:
#      path: /api-docs
#    swagger-ui:
#      path: /swagger-ui.html
#      disable-swagger-default-url: true
