server:
  port: 8080
  servlet:
      context-path: /todo/api/v1
spring:
  application:
    name: ${APPLICATION_NAME:TodoApp}
  datasource:
    url: jdbc:h2:~/testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  logging:
    level:
      root: INFO
      com.soprasteria.todo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  spring-doc:
#    api-docs:
#      path: /api-docs
#    swagger-ui:
#      path: /swagger-ui.html
#      disable-swagger-default-url: true
